-- 2021년 가입 회원 중 구매기록이 있는 회원 수와
-- 2021년에 가입한 전체 회원 중 해당 회원들(=2021년 가입 회원 구매기록이 있는 회원들)의 비율을
-- 년, 월별로 출력.
-- 비율은 소수점 첫째자리까지만
-- 전체 결과는 연 기준 오름차순, 월 기준 오름차순 정렬
-- 리텐션 구하는 문제.
WITH N AS (
    SELECT COUNT(DISTINCT USER_ID) AS N_CUSTOMERS
        FROM USER_INFO 
        WHERE YEAR(JOINED) = '2021'
)

SELECT YEAR(O.SALES_DATE) AS YEAR
     , MONTH(O.SALES_DATE) AS MONTH
     , COUNT(DISTINCT CASE WHEN YEAR(U.JOINED) = '2021' THEN O.USER_ID ELSE NULL END) AS PUCHASED_USERS
     , ROUND(COUNT(DISTINCT CASE WHEN YEAR(U.JOINED) = '2021' THEN O.USER_ID ELSE NULL END)/(SELECT N_CUSTOMERS FROM N), 1) AS PUCHASED_RATIO
    FROM ONLINE_SALE O
    LEFT JOIN USER_INFO U
        ON O.USER_ID = U.USER_ID
    GROUP BY YEAR, MONTH
    ORDER BY YEAR, MONTH 

# SELECT YEAR(SALES_DATE) AS YEAR
#      , MONTH(SALES_DATE) AS MONTH
#      , COUNT(DISTINCT USER_ID) AS PURCHASED_USERS
#     FROM ONLINE_SALE
#     WHERE USER_ID IN (
#         SELECT USER_ID
#             FROM USER_INFO 
#             WHERE YEAR(JOINED) = '2021'
#         )
#     GROUP BY YEAR, MONTH
#     ORDER BY YEAR, MONTH