-- 코드를 입력하세요
SELECT P.PRODUCT_ID
     , P.PRODUCT_NAME
     , SUM(O.AMOUNT) * P.PRICE AS TOTAL_SALES
    FROM FOOD_PRODUCT P
    LEFT JOIN FOOD_ORDER O
        ON P.PRODUCT_ID = O.PRODUCT_ID
    WHERE O.PRODUCE_DATE BETWEEN '2022-05-01 00:00:00' AND '2022-05-31 23:59:59'
    GROUP BY P.PRODUCT_ID
    ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID
