-- 대여기간 별 할인 : 7일 ~ 29일 / 30일 ~ 89일 / 90일 ~
-- "트럭"의 대여기록 별 대여 기록 ID, 대여 금액 출력
-- 대여 금액 내림차순, 대여 기록 ID 내림차순
        
-- 서브쿼리 : "대여기록이 있는" 트럭들의 정보
-- 메인쿼리 : 서브쿼리로부터 구한 대여기간, HISTORY ID 별 총 대여금액

-- 25.02.14
WITH TRUCK_RENTAL AS (
    SELECT HISTORY_ID
         , CAR_TYPE
         , DAILY_FEE
         , DATEDIFF(END_DATE, START_DATE) + 1 AS RENTAL_DAYS
         , CASE WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 7 THEN '할인 없음'
                WHEN DATEDIFF(END_DATE, START_DATE) + 1 BETWEEN 7 AND 29 THEN '7일 이상'
                WHEN DATEDIFF(END_DATE, START_DATE) + 1 BETWEEN 30 AND 89 THEN '30일 이상'
                WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
                END AS DURATION_TYPE
        FROM CAR_RENTAL_COMPANY_CAR C
        JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
            USING (CAR_ID)
        WHERE CAR_TYPE = '트럭'
)
SELECT HISTORY_ID
     , ROUND(DAILY_FEE * RENTAL_DAYS * (1-IFNULL(DISCOUNT_RATE, 0)/100), 0) AS FEE
    FROM TRUCK_RENTAL TR
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP
        ON TR.DURATION_TYPE = DP.DURATION_TYPE
        AND TR.CAR_TYPE = DP.CAR_TYPE
    ORDER BY FEE DESC, HISTORY_ID DESC
    







# WITH TRUCK_RENTAL AS (
#     SELECT HISTORY_ID
#          , CAR_TYPE
#          , DAILY_FEE
#          , DATEDIFF(END_DATE, START_DATE) + 1 AS RENTAL_DAYS
#          , CASE WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 7 THEN '할인 없음'
#                 WHEN DATEDIFF(END_DATE, START_DATE) + 1 BETWEEN 7 AND 29 THEN '7일 이상'
#                 WHEN DATEDIFF(END_DATE, START_DATE) + 1 BETWEEN 30 AND 89 THEN '30일 이상'
#                 ELSE '90일 이상'
#                 END AS DURATION_TYPE
#         FROM CAR_RENTAL_COMPANY_CAR C
#         JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
#             USING (CAR_ID)
#         WHERE C.CAR_TYPE = '트럭'
# ) 
# SELECT TR.HISTORY_ID
#      , ROUND(DAILY_FEE * RENTAL_DAYS * (1-IFNULL(DP.DISCOUNT_RATE, 0)/100)) AS FEE
#     FROM TRUCK_RENTAL TR
#     LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP
#         ON TR.DURATION_TYPE = DP.DURATION_TYPE
#         AND TR.CAR_TYPE = DP.CAR_TYPE
#     ORDER BY FEE DESC, HISTORY_ID DESC