-- 코드를 입력하세요
# 1. 22년 8월부터 10월까지의 총 대여 횟수가 5회 이상인 CAR_ID를 찾는다
# 2. 해당 CAR_ID에 문제에서 말한 조건을 걸어주어 출력한다.

SELECT EXTRACT(MONTH FROM START_DATE) AS MONTH
     , CAR_ID
     , COUNT(*) AS RECORDS
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY MONTH, CAR_ID
    HAVING CAR_ID IN (
        SELECT CAR_ID
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
            WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
            GROUP BY CAR_ID
            HAVING COUNT(*) >= 5
    )
    ORDER BY MONTH, CAR_ID DESC;