-- 2022년 1월 카테고리별 도서 판매량 합산
-- 카테고리, 총 판매량 리스트 출력
-- 카테고리 명 기준 오름차순 정렬

SELECT CATEGORY
     , SUM(SALES) AS TOTAL_SALES
    FROM BOOK B1
    JOIN BOOK_SALES B2
        ON B1.BOOK_ID = B2.BOOK_ID
    WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
    GROUP BY CATEGORY
    ORDER BY CATEGORY