-- 코드를 입력하세요
SELECT CATEGORY
     , PRICE AS MAX_PRICE
     , PRODUCT_NAME
    FROM (
    SELECT CATEGORY
         , PRICE
         , PRODUCT_NAME
         , DENSE_RANK() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS RANKING
        FROM FOOD_PRODUCT
        WHERE CATEGORY IN ('과자', '국', '식용유', '김치')
        ) AS B
    WHERE RANKING = 1
    ORDER BY MAX_PRICE DESC